### ISSUE TITLE
Make it work with Babel 7

### ISSUE THREAD

**Issue by gajus** [vitalets/babel-plugin-runtyper#13]
I have tried it on a project that uses Babel 7 and got bunch of errors, that I assume are due to the Babel 7 version:

```
{ Error: Cannot find module 'babel-types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:571:15)
    at Function.Module._load (internal/modules/cjs/loader.js:497:25)
    at Module.require (internal/modules/cjs/loader.js:626:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/gajus/Documents/dev/applaudience/cinema-data-scraper-sources/node_modules/babel-plugin-runtyper/src/binary/equal.js:3:11)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3) code: 'MODULE_NOT_FOUND' }
[..]

```

The errors are about missing dependencies (`babel-types` and `babel-template`).

Installing the missing dependencies makes the plugin work.

I am assuming those two dependencies could be moved from devDependencies to main dependencies and that could fix the issue (depending on how these dependencies are resolved).

**Comment by vitalets** [comment]
Thanks for report! Will fix it.
